[theme]
base="light"
primaryColor="#FF4B4B"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#31333F"
font="sans serif"

[client]
toolbarMode = "viewer"


[browser]
serverAddress = "streamlit-lstm"
gatherUsageStats = true
serverPort = 8501


[server]
address = "127.0.0.1"
port = 8501
enableCORS = false
headless = true